import type { AppProps } from 'next/app';
import Head from 'next/head';
import Layout from '@/layouts/Layout';
import '@/styles/globals.scss';

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>{process.env.NEXT_PUBLIC_SERVICE_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </>
    );
}
